/** Auto-generated by museum-games-catalog — do not edit. */
export type DiscoveredGame = {
	param: string;
	title: string;
	description: string;
	dimensions: '2d' | '3d';
	category?: 'demo';
	createdAt: number;
};

export const discoveredGames: DiscoveredGame[] = [
	{
		"param": "hello",
		"title": "Hello",
		"description": "",
		"dimensions": "3d",
		"createdAt": 1785668672113
	}
];
