/**
 * Vite plugin — discovers static/games JSON-LD worlds and writes
 * discoveredGames.ts so the nav picker stays in sync with the
 * filesystem (works with svelte-check; no virtual module).
 */
import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

export type DiscoveredGame = {
	param: string;
	title: string;
	description: string;
	dimensions: '2d' | '3d';
	category?: 'demo';
};

function prettifyParam(param: string): string {
	return (
		param
			.split(/[-_/]+/)
			.filter(Boolean)
			.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
			.join(' ') || param
	);
}

function walkJsonld(dir: string, base = ''): { param: string; filePath: string }[] {
	if (!fs.existsSync(dir)) return [];
	const out: { param: string; filePath: string }[] = [];
	for (const name of fs.readdirSync(dir)) {
		if (name.startsWith('.')) continue;
		const full = path.join(dir, name);
		const rel = base ? `${base}/${name}` : name;
		const stat = fs.statSync(full);
		if (stat.isDirectory()) {
			out.push(...walkJsonld(full, rel));
			continue;
		}
		if (!name.endsWith('.jsonld')) continue;
		out.push({ param: rel.replace(/\.jsonld$/i, ''), filePath: full });
	}
	return out;
}

function inferCategory(param: string): 'demo' | undefined {
	if (/(?:^|\/|-)demo(?:$|-)/i.test(param) || /demo/i.test(param)) return 'demo';
	return undefined;
}

function extractFromDoc(doc: unknown, param: string): DiscoveredGame {
	const root = doc && typeof doc === 'object' ? (doc as Record<string, unknown>) : {};
	let title: string | null = null;
	let dimensions: '2d' | '3d' = '3d';
	let description = typeof root.comment === 'string' ? root.comment.trim() : '';

	const graph = Array.isArray(root['@graph']) ? root['@graph'] : [];
	for (const node of graph) {
		if (!node || typeof node !== 'object') continue;
		const components = (node as { components?: Record<string, unknown> }).components;
		if (!components || typeof components !== 'object') continue;

		const editorScene = components.EditorScene as
			| { document?: { scene?: { displayName?: unknown } } }
			| undefined;
		const displayName = editorScene?.document?.scene?.displayName;
		if (typeof displayName === 'string' && displayName.trim()) {
			title = displayName.trim();
		}

		const profile = components.WorldProfile as { dimensions?: unknown } | undefined;
		if (profile?.dimensions === '2d') dimensions = '2d';
	}

	if (description.length > 160) description = `${description.slice(0, 157)}…`;

	return {
		param,
		title: title ?? prettifyParam(param),
		description,
		dimensions,
		category: inferCategory(param)
	};
}

function readGame(filePath: string, param: string): DiscoveredGame {
	try {
		const raw = fs.readFileSync(filePath, 'utf8');
		return extractFromDoc(JSON.parse(raw), param);
	} catch (err) {
		console.warn(`[museum-games] failed to read ${param}:`, err);
		return {
			param,
			title: prettifyParam(param),
			description: '',
			dimensions: '3d',
			category: inferCategory(param)
		};
	}
}

export function scanGamesCatalog(gamesDir: string): DiscoveredGame[] {
	return walkJsonld(gamesDir)
		.map(({ param, filePath }) => readGame(filePath, param))
		.sort((a, b) => a.param.localeCompare(b.param));
}

function catalogModuleSource(gamesDir: string): string {
	const games = scanGamesCatalog(gamesDir);
	return `/** Auto-generated by museum-games-catalog — do not edit. */
export type DiscoveredGame = {
	param: string;
	title: string;
	description: string;
	dimensions: '2d' | '3d';
	category?: 'demo';
};

export const discoveredGames: DiscoveredGame[] = ${JSON.stringify(games, null, '\t')};
`;
}

export function writeGamesCatalog(rootDir: string): string {
	const gamesDir = path.resolve(rootDir, 'static/games');
	const outFile = path.resolve(rootDir, 'src/lib/engine/discoveredGames.ts');
	fs.writeFileSync(outFile, catalogModuleSource(gamesDir));
	return outFile;
}

export function museumGamesCatalogPlugin(rootDir: string): Plugin {
	const gamesDir = path.resolve(rootDir, 'static/games');
	const outFile = path.resolve(rootDir, 'src/lib/engine/discoveredGames.ts');

	const write = () => {
		writeGamesCatalog(rootDir);
	};

	// Ensure svelte-check / cold imports see a fresh catalog even before Vite boots.
	write();

	return {
		name: 'museum-games-catalog',
		buildStart() {
			write();
		},
		configureServer(server) {
			server.watcher.add(gamesDir);
			const invalidate = (file: string) => {
				const normalized = file.replace(/\\/g, '/');
				if (!normalized.includes('/games/')) return;
				if (!normalized.endsWith('.jsonld')) return;
				write();
				const mod = server.moduleGraph.getModuleById(outFile);
				if (mod) server.moduleGraph.invalidateModule(mod);
				server.ws.send({ type: 'full-reload' });
			};
			server.watcher.on('add', invalidate);
			server.watcher.on('change', invalidate);
			server.watcher.on('unlink', invalidate);
		}
	};
}
