/** Auto-generated by museum-games-catalog — do not edit. */
export type DiscoveredGame = {
	param: string;
	title: string;
	description: string;
	dimensions: '2d' | '3d';
	category?: 'demo';
};

export const discoveredGames: DiscoveredGame[] = [
	{
		"param": "agent-demo",
		"title": "Agent Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "alarms-demo",
		"title": "Alarms Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "animated-npc-demo",
		"title": "Animated Npc Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "arena",
		"title": "Arena",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "blank",
		"title": "Blank",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "blank2d",
		"title": "Blank2d",
		"description": "",
		"dimensions": "2d"
	},
	{
		"param": "circuit",
		"title": "Circuit",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "collect",
		"title": "Collect",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "collect-race",
		"title": "Collect Race",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "collections-demo",
		"title": "Collections Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "collision-demo",
		"title": "Collision Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "craftpunk/commons",
		"title": "Craftpunk Commons",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "events-demo",
		"title": "Events Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "gallery",
		"title": "Gallery",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "input-demo",
		"title": "Input Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "orbit",
		"title": "Orbit",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "parkour",
		"title": "Parkour",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "physics",
		"title": "Physics",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "physics-pit",
		"title": "Physics Pit",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "platformer2d",
		"title": "Platformer2d",
		"description": "",
		"dimensions": "2d"
	},
	{
		"param": "player-avatar-override",
		"title": "Player Avatar Override",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "playground",
		"title": "Playground",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "powder/slope",
		"title": "Powder Slope",
		"description": "",
		"dimensions": "3d"
	},
	{
		"param": "rooms-demo",
		"title": "Rooms Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "scripts-demo",
		"title": "Scripts Demo",
		"description": "",
		"dimensions": "3d",
		"category": "demo"
	},
	{
		"param": "silicon-city",
		"title": "Silicon City",
		"description": "Walk the machine you're running on. Every building is a live IORegistry node on this MacBookPro18,2 (Apple M1 Max, 64 GB) — height is how much of the system …",
		"dimensions": "3d"
	},
	{
		"param": "sprites-demo",
		"title": "Sprites Demo",
		"description": "",
		"dimensions": "2d",
		"category": "demo"
	},
	{
		"param": "tower",
		"title": "Tower",
		"description": "",
		"dimensions": "3d"
	}
];
